version: '2.1'

volumes:
  traefik-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  alertmanager-data:
    driver: local

networks:
  monitoring:
    driver: bridge  

services:

  # Internal reverse proxy
  traefik:
    image: traefik:v1.7.16-alpine
    container_name: traefik
    expose:
      - 80
      - 8080    
    ports:
      - "80:80"
    networks:
      - monitoring
    volumes:
      - traefik-data:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    command: "-c /etc/traefik/traefik.toml
              --web
              --api
              --docker
              --docker.domain='${FQDN}'
              --docker.endpoint=unix:///var/run/docker.sock
              --docker.watch
              --metrics
              --metrics.prometheus
              "
    labels:
      - SERVICE_IGNORE=true
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip:/traefik"
      - "traefik.port=8080"      
    security_opt:
      - label:disable

  # Exporter host metrics
  nodeexporter:
    image: prom/node-exporter:v0.18.1
    container_name: node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring
    labels:
      - "SERVICE_TAGS=node_exporter"
      - "traefik.enable=false"    

  # Exporter docker metrics
  cadvisor:
    image: google/cadvisor:v0.32.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    expose:
      - 8080
    networks:
      - monitoring
    labels:
      - "SERVICE_TAGS=cadvisor"
      - "traefik.enable=false"

  # Metrics database
  prometheus:
    image: prom/prometheus:v2.12.0
    container_name: prometheus
    restart: unless-stopped    
    volumes:
      - ./resources/prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=200h'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - "--web.external-url=http://${FQDN}/prometheus/"
      - "--web.route-prefix=/"
    expose:
      - 9090 
    networks:
      - monitoring
    labels:
      - "SERVICE_TAGS=prometheus"
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip:/prometheus"
      - "traefik.port=9090"

  # Alertmanager
  alertmanager:
    image: prom/alertmanager:v0.19.0
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - ./resources/alertmanager/:/etc/alertmanager/
      - alertmanager-data:/prometheus    
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - "--web.external-url=http://${FQDN}/alertmanager/"
      - "--web.route-prefix=/"
    expose:
      - 9093
    networks:
      - monitoring
    labels:
      - "SERVICE_TAGS=alertmanager"
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip:/alertmanager"
      - "traefik.port=9093"

  # Metrics dashboard
  grafana:
    image: grafana/grafana:6.3.5
    container_name: grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - ./resources/grafana/providers:/etc/grafana/provisioning/dashboards/
      - ./resources/grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./resources/grafana/dashboards:/var/lib/grafana/dashboards/    
      - grafana-data:/var/lib/grafana
    environment: 
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false     
      - GF_SERVER_ROOT_URL=http://${FQDN}/grafana
    expose:
      - 3000 
    networks:
      - monitoring
    labels:
      - "SERVICE_TAGS=grafana"
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip:/grafana"
      - "traefik.port=3000"
