version: '2.1'

volumes:
  redis-data:
    driver: local

networks:
  monitoring:
    driver: bridge  

services:

  # Redis
  redis:
    image: redis:4.0.14
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command:
      - "--appendonly yes"
    expose:
      - 6379
    networks:
      - monitoring
    labels:
      - "SERVICE_TAGS=redis"
      - "traefik.enable=false"

  # Exporter redis metrics
  redisexporter:
    image: oliver006/redis_exporter:v1.2.0
    container_name: redis_exporter
    restart: unless-stopped
    depends_on: 
      - redis
    environment:
      - REDIS_ADDR=redis://redis:6379
    expose:
      - 9121
    networks:
      - monitoring
    labels:
      - "SERVICE_TAGS=redis_exporter"
      - "traefik.enable=false"    

