global:
  scrape_interval:     10s
  evaluation_interval: 10s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'


# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node'
    scrape_interval: 10s
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    scrape_interval: 10s
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'redis'
    scrape_interval: 10s
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'mongodb'
    scrape_interval: 10s
    static_configs:
      - targets: ['mongodb_exporter:9216']

  - job_name: 'haproxy'
    scrape_interval: 10s
    static_configs:
      - targets: ['haproxy_exporter:9101']

  - job_name: 'nats'
    scrape_interval: 10s
    static_configs:
      - targets: ['nats_exporter:7777']

  - job_name: 'elasticsearch'
    scrape_interval: 10s
    static_configs:
      - targets: ['elasticsearch_exporter:9114']

remote_write:
  - url: "http://victoriametrics:8428/api/v1/write"
    queue_config:
      max_samples_per_send: 10000

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'